docs/03consensus/light_clients.md
Small updates for on/off and slot/sub-slot.
=> update light client

docs/09keys/keys-and-signatures.md
Updated status of Chia's compliance with BLS 2 and 4.
=> Update status wrt BLS 2 and 4

docs/01introduction/what-is-chia.md
Includes new links to CATs and offer files.
=> Add new info an links to key features

docs/12rpcs/nft_rpcs.mdx, docs/13cli/nft_cli.mdx
First step to addressing https://github.com/Chia-Network/chia-blockchain/issues/12227
Adds disclaimers to CLI and RPC docs with some explanation of the context and terminology
#132 can then be merged after v1.4.1
=> Add disclaimer for series/edition number

docs/04coin-set-model/addresses.md
#136 did not deploy due to a formatting error
=> Fix formatting for MDX

docs/cat2/cat2-issuance.mdx, docs/cat2/cat2-snapshot.mdx
Also require installing from source.
=> Add recommended fee

docs/13cli/cat_admin.mdx, docs/cat2/cat2-issuance.mdx, docs/cat2/cat2-snapshot.mdx
1. Add CAT-admin CLI usage doc
2. Add install from source (and from main) info
3. Update multi-issuance puzzle/solution
=> Update CAT2 info

docs/cat2/cat2-issuance.mdx, docs/cat2/cat2-snapshot.mdx
- add taildatabase info
- add surrounding () to multi-issuance instructions
- add link to snapshot zip file
- update language to indicate that CAT1 is EOL
=> Cat2 updates

docusaurus.config.js.j2, src/components/HomepageFeatures.js, src/pages/index.js, src/theme/prism-chialisp.js, src/theme/prism-dark-theme-chialisp.js, src/theme/prism-include-languages.js, src/theme/prism-light-theme-chialisp.js
Config changes to help sync up with staging
=> Cleaned up config

docs/12rpcs/simulator.mdx, docs/13cli/simulator.mdx
=> Add simulator CLI and RPC docs

docs/12rpcs/simulator.mdx, docs/13cli/simulator.mdx
=> Add simulator links

docs/12rpcs/rpcs.md
Simple change to add the datalayer port in the main RPC doc
=> Add datalayer port to RPC default port list

docs/12rpcs/datalayer_rpcs.mdx
=> Delete mirror takes coin_id and not id

docs/cli-reference/custody-tool.md
=> Update links to custody guides

docs/resources/faq.md
=> Update FAQ connect to trusted peer

docs/rpc-reference/nfts.mdx
=> Add new NFT RPCs for 1.6.1

docs/resources/faq.md
=> Modify headers for better menu heirarchy. Add new NFT info for 1.6.1.

docs/rpc-reference/offers.mdx
=> Add new RPCs for message sending and signing

docs/resources/faq.md
=> Add question about sending/receiving notifications

docs/cli-reference/datalayer.mdx
=> delete_mirror uses coin_id

docs/rpc-reference/nfts.mdx
=> Edition changes

docs/rpc-reference/cadt.mdx, sidebars.js
=> Add CADT RPC reference

docs/consensus/light-clients.md
=> Proof of Space -> Proof of Space and Time

docs/resources/faq.md
=> Add questions about exe location and usage

docs/resources/references.md
=> Add Eric's presentation to Video resources

docs/cli-reference/wallet.mdx, docs/resources/faq.md
* Add new info regarding coin list, split, and combine commands
* Fix broken FAQ links
* Update obsolete FAQ links
* Update questions in FAQ
=> Coin commands

docs/plotting/k-sizes.md, docs/plotting/plotting-basics.md, docs/plotting/plotting-software.md, docs/plotting/ssd-endurance.md
=> Jm plotting

docs/farming/farming-considerations.md, docs/farming/reference-farming-hardware.md
adding farming considerations page and reference farming doc
=> updating reference farming doc

docs/cli-reference/simulator.md, docs/guides/simulator-user-guide.md
Switch `cdv sim` for `chia dev sim`
instructions still need to be updated, but at least people can run them now.
=> Update Simulator docs for CLI changes.

docs/guides/simulator-user-guide.md, docs/rpc-reference/dids.md, docs/rpc-reference/farmer.md, docs/rpc-reference/full-node.md, docs/rpc-reference/harvester.md, docs/rpc-reference/nfts.md, docs/rpc-reference/offers.md, docs/rpc-reference/simulator.md, docs/rpc-reference/wallet.md
Previously, the RPC docs were arranged by how they were written in code. This isn't optimal for developers scanning the docs, so this PR arranges them alphabetically.
=> Rpc arrange

docusaurus.config.js, static/js/matomo.js
Added Matomo analytics to the site. Matomo is a privacy-friendly site analytics tool. Learn more here: https://matomo.org/privacy/
=> Add matomo

docs/guides/seeder-user-guide.md
This makes the instructions a lot easier to follow
=> make seeder guide more understandable

docs/cli-reference/cli.md
DB: inclusion of backup and validate commands
Plotters: update with redirect to the plotters cli page
General: updated full list of base commands and options
=> cli updates for db, plotters, and general

docs/resources/faq.md, docs/rpc-reference/wallet.md
- Inclusion of FAQ items for moving and upgrading the blockchain database.
- Fix link in wallet RPC get_transaction
=> Database move and upgrade, misc fixes

docs/rpc-reference/rpc.md
added a C# client in addition to python and Javascript.
The library is regularly updated to keep up to date and offers some unique additional functions utilizing the rpc protocol (such as calculating a coin ID)
=> Added C# client reference

docs/academy/academy-intro/academy-overview.md, docs/academy/chialisp/chialisp-intro.md, docusaurus.config.js, sidebars.js
This pr integrates the academy to the docs site including:
- academy overview(template)
- clsp intro (first lesson)
Note - this commit does not contain the runnable cslp module due to dependency discrepancies, a future iteration will include that module.
=> academy and clsp intro

docusaurus.config.js
this removes the academy from the top bar with the intention of it being readded once there is more content added
=> remove academy from top bar

package-lock.json
various dependency version bumps - more dependency issues outstanding, this is but step 1
=> version bumps

docs/consensus/proof-of-space.md
This pr updates the PoS construction link on our docs page to the new home
=> fix link in proof-of-space.md

README.md
replaces yarn commands in the readme for npm and relays the exact commands being run in github CI
=> readme-updates-npm

docs/academy/blockchain-basics/block-formation-basics.md, docs/academy/blockchain-basics/coinset-basics.md, docs/academy/blockchain-basics/consensus-basics.md, docs/academy/blockchain-basics/security-basics.md, docs/academy/blockchain-basics/timelord-basics.md, sidebars.js
adds all of the blockchain basics lessons to chia academy and the sidebar
=> Academy bchain basics

docs/getting-started/testnets.md
- typo fix in cofarming initial CHI_ROOT export
- update private testnet to include genesis challenge link and improve formatting
=> Update cofarming and private testnet

docs/architecture/mempool.md
adds specific conditions for replace by fee and link to the codebase logic for rbf.
Thank you Arvid for consolidating all of the information!
=> Update rbf specifics

docs/farming/pool-farming.md
=> Remove extra ` in in pool-farming.md

docs/guides/crash-course/state.md
Responding to https://github.com/Chia-Network/chia-docs/issues/457
=> Add npm install instruction

docs/reference-client/check-if-things-are-working.md
add block validation time commands for full node functionality
=> add block validation time commands

docs/coin-set-model/costs.md
inclusion of most basic operations, their clvm cost, and effective fees
=> add clvm costs to docs

docs/resources/references.md
Adds link for Bram's 2022 Off the Chain talk overviewing custody solutions
=> inclusion of Brams 2022 Off the Chain talk

docs/guides/crash-course/chialisp-and-typescript.md
updated packages in chialisp-and-typescript.md from rigidity's namespace to CNI official
=> Update packages noted in chialisp-and-typescript.md

docs/resources/k-sizes.md
include storage requirements for uncompressed plots in k-size page
=> include storage requirements in k-size page

docs/academy/academy-intro/academy-home.md, docusaurus.config.js, src/css/custom.css
- adds card based carousel to academy home for review
=> Academy home carousel

docs/guides/dao/dao-cli-guide.md, docs/rpc-reference/daos.md, docs/rpc-reference/wallet.md
Add documentation and examples for create_new_wallet RPC to create and join a DAO
=> create/join DAO RPC doc

docs/getting-started/testnets.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/getting-started/testnets.md
update community txch faucet link
=> update community txch faucet link

docs/guides/custody/prefarm-audit.md
the link in the prefarm to the flowchart is incorrect, this fixes that
=> Update prefarm flowchart link

docs/cli-reference/offers.md
Per this PR: https://github.com/Chia-Network/chia-blockchain/pull/17220/files
=> Add --override flag to make_offer command

docs/architecture/mempool.md
...along with other updates to the mempool, including the 60% limit and the 20-block size.
=> Add mempool scenario 4

docs/green-paper/green-paper-abstract.md
=> Update link to green-paper-precursor

docs/consensus/forks.md
just a minor change to set the correct date of the last change in the table of forks to the last change made (according to git blame)
=> fix date of last table change

docs/rpc-reference/offers.md, docs/rpc-reference/wallet.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/rpc-reference/offers.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/rpc-reference/wallet.md
=> update rpc sort_key information

docs/walletconnect/offers.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/walletconnect/offers.md
=> update offer trade status info

docs/guides/seeder-user-guide.md
We need to highlight some changes that came from poetry in 2.4.2
=> Poetry impacted Seeder Users Guide

docs/farming/dual-farming-testnet-mainnet.md
changes to the config file over the years deprecated the script this update brings it in line with the current config
resolves #638
=> update dual farming yq script

docs/rpc-reference/nfts.md
related code:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/rpc/wallet_rpc_api.py
( please test )
=> fixed example; target_address_list -> target_list to match docs & code

docs/rpc-reference/wallet.md
=> update send multi wallet rpc

docs/rpc-reference/full-node.md
i'm guessing it should say yet? additional info would be great on this also...
=> yes -> yet? Update full-node.md

docs/green-paper/green-paper-introduction.md
Should be price and not prize.
=> Fix typo in green-paper-introduction.md

docs/resources/faq.md
Why won't you just copy the description over I made on three other pages... removing USDS and Offerbin mentions, updating some answers to questions, and fixing some `http` `ttp` links.
=> OverActiveBladderSystem strongly disagrees with learning how to use GitHub faq.md-patch-1

docs/block-validation/block-validation.md
to match soft-fork 2. The 5 minute timestamp validation window is 2 minutes
=> update block validation documentation

docs/troubleshooting/logging-reference.md
OABS Update logging-reference.md updating some file size information, adding in log level chart, and some additional lines changed.
=> OABS Update logging-reference.md

docs/guides/crash-course/cats-offers-nfts.md
remove offerbin.io (which now redirects to an unrelated website) and replace with dexie.space
There are probably more places where Offerbin needs to be removed
=> OABS Update cats-offers-nfts.md

docs/chia-blockchain/green-paper/green-paper-introduction.md
=> OABS Update green-paper-introduction.md

docs/cloud-wallet/known-issues.md
I have verified that the three removed issues have each been fixed. The remaining issues listed are long-standing.
=> Remove fixed issues
