src/css/custom.css
"Chia Documentation" on home wasn't responsive, now it is
=> responsive title font size

static/CNAME
According to https://github.com/facebook/docusaurus/issues/3889 a CNAME file is required within the static directory to retain custom domain settings in GH Pages
=> Add cname file

docs/03consensus/consensus_intro.md
Links into our consensus should see its formal name first.
=> Add and Time

docs/04coin-set-model/coin_set_vs_account.md, docs/04coin-set-model/intro.md
Corrected the wording in the coin spend information to be consistent with the desired final state.
=> fixed incorrect description of coin spend

docs/rpc-reference/datalayer.mdx, docs/rpc-reference/nfts.mdx, docs/rpc-reference/offers.mdx
Some of our RPC docs specify the fee is in mojos and some do not.  Since we use XCH in the GUI and CLI, it is important we are very clear about the units for fees in the RPC as it is not intuitive.  This PR adds clarifying text on any RPC reference to fees where the units are not specified.
=> specify the fee is in mojos in RPC docs

docs/12rpcs/nft_rpcs.mdx
1) `nft_get_info` does not require a `wallet_id`
2) `nft_mint_nft` uses `edition_total` _not_ `edition_count`
Of note: the example response for `nft_get_nfts` uses `edition_count` and `edition_number`. The type declaration for `NFTInfo` in nft_info.py has `series_total` & `series_number`. So not sure if those are being remapped somewhere during serialization, is an oversight or a mistake in the example. It would make sense for it to be made consistent with the edition nomenclature.
=> Two corrections based on 1.5.0 code

docs/rpc-reference/wallet.mdx
=> address flag in verify_signature RPC is not required

docs/cli-reference/cli.md
The docs still reference the old Windows paths (with version 1.1.3) as an example. Left the example unchanged but added the new non-versioned paths depending on whether it was installed as local user or for all users.
=> update Windows CLI paths

docusaurus.config.js
Closes #287 
"Edit this page" links do not work because the `editUrl` in `docusaurus.config.js` is clearly templated but is never expanded for `REPOSITORY_NAME`
My quick look at docusaurus docs doesn't show any information on templating the config.
I also didn't find anywhere else `REPOSITORY_NAME` is used, so I ruled out it was injected at build time (like in github workflows or build scripts).
This change hardcodes the `editUrl` to what would be the expanded template. 
A simple test of rewriting the URL I was directed to with what's involved in this change confirms that it will place the user on the associated markdown file that they can then edit.
=> fix "Edit this page" links everywhere

docs/resources/references.md
We were direct linking to the original Green Paper. If there is a way to relatively link this as a URI, happy to take that approach instead.
=> Update link to Green Paper

.github/workflows/deploy-pages.yml
Trunk deployments are starting to complain about lack of github actor permissions. Adding content scope explicitly.
=> Add permissions block with contents write scope

.github/workflows/deploy-pages.yml
postBuffer documented at: https://git-scm.com/docs/git-config#Documentation/git-config.txt-httppostBuffer
Needed due to commit/push errors over https related to the remote hanging up unexpectedly
This increases the post buffer size from 1MB (default) to 10MB
=> Add git https postBuffer option

docs/guides/chialisp-primer/first-smart-coin.md
According to chiadevs on keybase, the documented opc command was changed from outputting two values to just one.
=> Fix first smart coin docs to match new command behavior

docs/reference-client/node-syncing.md
The introducer nodes listed on the chia docs page are outdated. (https://docs.chia.net/node-syncing/#speed-up-connecting-to-nodes)
This PR updates the introducer nodes to align with what is available in the github wiki:
https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444#speed-up-connecting-to-nodes
=> Update introducer nodes

docs/guides/custody/prefarm-audit.md, docs/guides/tutorials/prefarm-audit.md, sidebars.js
This tutorial instructs users on how to use the chia custody tool to audit the chialisp puzzles in which the prefarm is held.
The tutorial also has a high level overview of how to perform this audit using the clsp puzzles themselves.
=> prefarm-audit-tutorial

docs/guides/cat/cat-creation-tutorial.md
The current tutorial does not include the chia dev tool installation for linux and is also missing the dependencies installation for windows.
=> Update cat admin tool tutorial for dependencies install

docs/walletconnect/nfts.md
- added mintNFT
- cleaned up the NFT types to ensure alignment with codebase
=> Add mintNFT to nfts.md

docs/resources/faq.md
while updating the kb articles with links to their corresponding docs I noticed this last article that was not migrated with the original batch.
Once this is migrated, all kb articles will be within the docs site and a sunset period will start
=> migrate last kb article to docs

docs/architecture/mempool.md, docs/resources/faq.md
Adding more detailed info about how a transaction is prioritized in the mempool.
=> Mempool info

src/components/HomepageFeatures.js
This pr removes the developer forum from the docs landing page in accordance with the sunsetting of this platform
=> sunsetting developer forum

docs/academy/academy-intro/academy-overview.md, docs/academy/chialisp/chialisp-intro.md, package-lock.json, package.json, src/components/Runnable.tsx, src/utils/stringify.ts
- integrates runnable clsp for the academy overview and first clsp lesson
=> runnable clsp integration

docusaurus.config.js
adding the trailing slash eliminates a warning in build and aids with seo links
=> add trailing slash to config

docs/rpc-reference/dids.md
Previously indicated that coinID is the wallet ID, corrected this and added clarity on the format for the coinID
=> Fix did_get_info information and add clarity

docs/guides/crash-course/state.md
add info for Genesis used in state example, resolves #466
=> add info for Genesis used in state example

docs/resources/faq.md
adds the instructions for using the official chia blockchain snapshot torrent
=> include snapshot torrent instructions

docs/rpc-reference/nfts.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/rpc-reference/nfts.md
`ignore_size_limit` is not honored downstream and so it's effectively always `False`.
=> Update nft_get_nfts docs on ignore_size_limit

docs/academy/academy-intro/academy-home.md, docusaurus.config.js, src/css/custom.css
fix for mobile device navigation
=> carousel fix

docs/academy/academy-intro/academy-home.md, src/css/custom.css
the manual changes to the list item css caused unforeseen issues with rendering lists on the rest of the site, this resolves that by making the custom list item css its own unique name `c-ol` and `c-li` instead of `ol` and `li`.
=> fix list item in css

docs/rpc-reference/full-node.md
In the example for how to escape quotes in windows the slash does not show up since it is not escaped, Replaced \ with \\.
=> Fixed \ not showing up since it is escaped

docs/getting-started/installation.md
- ensure removal all virtual environments are noted in update instructions
=> update windows source install

docs/guides/nft/nft-bulk-mint.md
macOS needs to have single quotes around the square brackets or zsh will run into errors. 
This change will also work on the other OS's without issue
resolves #640
=> Update pip install command

docs/getting-started/timelords.md
Modified the "chia start..." command to remove typos
=> Resolve typos in bluebox timelord install from source instructions

docs/consensus/forks.md
I updated the status for Block `5 940 000` "Disallow infinity G1 points" to `Activated` set the day for the last two activated forks.
=> Update activated forks date and status (Block 5 940 000, Disallow infinity G1 points)

docs/protocol/wallet-protocol.md
this draft is for review purposes, more commits are needed before this is final.
=> Update wallet protocol doc

docs/rpc-reference/rpc.md
2.5.1 introduced new rpcs to control the services log levels. This pr adds those endpoints to the rpc overview doc page.
=> Include log level rpcs

docs/troubleshooting/node-syncing.md
Expanding some details around port 8444, mention of VPN for configuring port forwarding, mention about multiple nodes on the same network requiring additional configurations.
=> OABS Update node-syncing.md

docs/resources/faq.md
minimum MacOS updated, 256 to 512 GB SSD recommendation
=> OABS Update faq.md
